version: "2"

services:
    mysql:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_USER: ${MYSQL_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DB}
      volumes:
        - mysql-vol:/var/lib/mysql
      ports:
        - ${MYSQL_PORT}:3306
      network_mode: bridge