name: PostgreSQL
description: |
  PostgreSQL, often simply "Postgres", is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards-compliance.
version: "10.1"
category: Database
