version: "2"

services:
  mysql:
   image: mysql
   command: [--character-set-server=utf8, --default-authentication-plugin=mysql_native_password]
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: example
     MYSQL_DATABASE: test
   volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/sql:/docker-entrypoint-initdb.d
   ports:
     - 3306:3306
  grafana:
   image: grafana/grafana
   volumes:
     - ./grafana_data:/var/lib/grafana
   ports:
     - 3000:3000