superset:
  image: jigsawinc/docker-superset:latest
  environment:
    - SUPERSET_USER=${SUPERSET_USER}
    - SUPERSET_FIRSTNAME=${SUPERSET_FIRSTNAME}
    - SUPERSET_LASTNAME=${SUPERSET_LASTNAME}
    - SUPERSET_EMAIL=${SUPERSET_EMAIL}
    - SUPERSET_PASSWORD=${SUPERSET_PASSWORD}
  ports:
    - ${SUPERSET_PORT}:8088/tcp
  restart: always
  volumes:
    - superset-vol:/superset
